// rslib/solid-basic/src/Button.tsx
import type { Component } from 'solid-js';
import './button.css';

export interface ButtonProps {
  primary?: boolean;
  backgroundColor?: string;
  size?: 'small' | 'medium' | 'large';
  label: string;
  onClick?: () => void;
}

export const Button: Component<ButtonProps> = ({
  primary = false,
  size = 'medium',
  backgroundColor,
  label,
  onClick,
}) => {
  const mode = primary ? 'demo-button--primary' : 'demo-button--secondary';

  return (
    <button
      type="button"
      class={`demo-button demo-button--${size} ${mode}`}
      style={{ 'background-color': backgroundColor }}
      onClick={onClick}
    >
      {label}
    </button>
  );
};

// rslib/module-doc/src/Button.tsx
import './button.css';

export interface ButtonProps {
  /**
   * Whether the button is primary
   * @default true
   */
  primary?: boolean;
  /**
   * Background color of the button
   */
  backgroundColor?: string;
  /**
   * Size of Button
   * @default 'large'
   */
  size?: 'small' | 'medium' | 'large';
  /**
   * Label of the button
   */
  label: string;
}

export const Button = ({
  primary = true,
  size = 'large',
  backgroundColor,
  label,
  ...props
}: ButtonProps) => {
  const mode = primary ? 'demo-button--primary' : 'demo-button--secondary';
  return (
    <button
      type="button"
      className={['demo-button', `demo-button--${size}`, mode].join(' ')}
      style={{ backgroundColor }}
      {...props}
    >
      {label}
    </button>
  );
};
