// rsbuild/react-unocss/src/App.tsx
import React, { useState } from 'react';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="text-center">
      <header className="bg-#282c34 min-h-100vh flex flex-col items-center justify-center color-white">
        <h1 className="mt-2em animate-bounce-alt animate-duration-2s">Hello Rsbuild + React!</h1>
        <p>
          <button
            className="bg-blue-400 hover:bg-blue-500 text-sm text-white font-mono font-light py-2 px-4 rounded border-2 border-blue-200 dark:bg-blue-500 dark:hover:bg-blue-600"
            type="button"
            onClick={() => setCount((count) => count + 1)}
          >
            count is: {count}
          </button>

          <button
            bg="blue-400 hover:blue-500 dark:blue-500 dark:hover:blue-600"
            text="sm white"
            font="mono light"
            p="y-2 x-4"
            m="l-1em"
            border="2 rounded blue-200"
            type="button"
            onClick={() => setCount((count) => count + 1)}
          >
            count is: {count}
          </button>
        </p>
        <p>
          Edit <code>App.tsx</code> and save to test HMR updates.
        </p>
        <p>
          <a
            className="color-#61dafb"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
          {' | '}
          <a
            className="color-#61dafb"
            href="https://rsbuild.rs"
            target="_blank"
            rel="noopener noreferrer"
          >
            Rsbuild Docs
          </a>
        </p>
      </header>
    </div>
  );
}

export default App;

// rspack/solid/src/App.jsx
import logo from './logo.svg';
import styles from './App.module.css';
import { createSignal } from 'solid-js';
import Message from './Message.jsx';
function App() {
  const [count, setCount] = createSignal(1);
  const increment = () => setCount(count() + 1);
  return (
    <div class={styles.App}>
      <header class={styles.header}>
        <img src={logo} class={styles.logo} alt="logo" />
        <p>
          Edit <code>src/App.jsx</code> and save to reload.
        </p>
        <a
          class={styles.link}
          href="https://github.com/solidjs/solid"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Solid
        </a>
        <button type="button" onClick={increment}>
          {count()}
        </button>
        <Message />
      </header>
    </div>
  );
}

export default App;
