// rstest/rspack-adapter/src/App.tsx
import { useState } from 'react';
import reactLogo from './assets/react.svg';
import './App.css';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <div>
        <a href="https://react.dev" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Rspack + React + TypeScript</h1>
      <div className="card">
        <button type="button" onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">Click on the Rspack and React logos to learn more</p>
    </div>
  );
}

export default App;

// rspack/solid/src/App.jsx
import logo from './logo.svg';
import styles from './App.module.css';
import { createSignal } from 'solid-js';
import Message from './Message.jsx';
function App() {
  const [count, setCount] = createSignal(1);
  const increment = () => setCount(count() + 1);
  return (
    <div class={styles.App}>
      <header class={styles.header}>
        <img src={logo} class={styles.logo} alt="logo" />
        <p>
          Edit <code>src/App.jsx</code> and save to reload.
        </p>
        <a
          class={styles.link}
          href="https://github.com/solidjs/solid"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Solid
        </a>
        <button type="button" onClick={increment}>
          {count()}
        </button>
        <Message />
      </header>
    </div>
  );
}

export default App;
